export const courses = [
  {
    title: "React for Beginners",
    description: "Learn React.js from scratch.",
    category: "Programming",
    duration: 10,
    price: 50,
    instructor: "John Doe",
    ratings: 4.5,
  },
  {
    title: "Advanced React",
    description: "Deep dive into React.js concepts.",
    category: "Programming",
    duration: 15,
    price: 70,
    instructor: "Jane Smith",
    ratings: 4.8,
  },
  {
    title: "UI/UX Design Basics",
    description: "Master the basics of UI/UX design.",
    category: "Design",
    duration: 8,
    price: 40,
    instructor: "Alice Brown",
    ratings: 4.3,
  },
  {
    title: "Python for Data Science",
    description: "Learn Python with a focus on data science.",
    category: "Programming",
    duration: 12,
    price: 60,
    instructor: "Bob Johnson",
    ratings: 4.7,
  },
  {
    title: "Digital Marketing 101",
    description: "An introduction to digital marketing strategies.",
    category: "Marketing",
    duration: 6,
    price: 30,
    instructor: "Eve Wilson",
    ratings: 4.2,
  },

  {
    title: "Mastering JavaScript",
    description: "A comprehensive guide to JavaScript.",
    category: "Programming",
    duration: 15,
    price: 70,
    instructor: "Jane Smith",
    ratings: 4.8,
  },
  {
    title: "Python for Data Science",
    description: "Explore the fundamentals of data science with Python.",
    category: "Data Science",
    duration: 12,
    price: 60,
    instructor: "Alice Johnson",
    ratings: 4.7,
  },
  {
    title: "Web Development Bootcamp",
    description: "Learn to build full-stack web applications.",
    category: "Web Development",
    duration: 20,
    price: 100,
    instructor: "Mark Brown",
    ratings: 4.9,
  },
  {
    title: "Introduction to Machine Learning",
    description: "Learn the basics of machine learning and AI.",
    category: "Artificial Intelligence",
    duration: 18,
    price: 85,
    instructor: "Emily Davis",
    ratings: 4.6,
  },
  {
    title: "Graphic Design Essentials",
    description: "Master the basics of graphic design and Adobe tools.",
    category: "Design",
    duration: 8,
    price: 45,
    instructor: "Chris Wilson",
    ratings: 4.3,
  },
  {
    title: "Advanced Excel Techniques",
    description: "Boost your productivity with Excel.",
    category: "Business",
    duration: 6,
    price: 30,
    instructor: "Lisa Green",
    ratings: 4.2,
  },
  {
    title: "SEO and Digital Marketing",
    description: "Learn strategies to improve your website's SEO.",
    category: "Marketing",
    duration: 9,
    price: 55,
    instructor: "Paul White",
    ratings: 4.4,
  },
  {
    title: "Cybersecurity Fundamentals",
    description: "Understand the essentials of cybersecurity.",
    category: "Cybersecurity",
    duration: 14,
    price: 75,
    instructor: "Michael Scott",
    ratings: 4.7,
  },
  {
    title: "Photography Basics",
    description: "Start your journey in photography.",
    category: "Photography",
    duration: 5,
    price: 25,
    instructor: "Anna Lopez",
    ratings: 4.1,
  },
  {
    title: "Public Speaking Mastery",
    description: "Improve your public speaking and presentation skills.",
    category: "Personal Development",
    duration: 7,
    price: 40,
    instructor: "Kevin Lee",
    ratings: 4.5,
  },
];
